name:                shunting-yard
version:             0.1.0.0
github:              "hilltse/shunting-yard-hs"
license:             BSD3
author:              "Hill Tse"
maintainer:          "hftseab@ust.hk"
copyright:           "2020 Hill Tse"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hilltse/shunting-yard-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

tests:
  shunting-yard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shunting-yard
